### ISSUE TITLE
Checkbox / Radio Button selection

### ISSUE THREAD

**Issue by CandyGumdrop** [fstirlitz/thickice#2]
This theme works very well except that the checkboxes and radio buttons look exactly the same whether they are selected or not selected.

In the GTK+2 ThinIce, checkboxes and radio buttons appear inset when selected and outset when deselected, however they always appear outset in ThickIce.  This seems to be the same with toggle buttons too.

I had a quick look at trying to fix it in the CSS but I've not done much with GTK+ themes before and I couldn't fix it.

I don't know whether this something which can be fixed in the stylesheet, or has to be fixed in the rendering engine, or is something which worked before and has stopped working since a recent GTK+ version.  My GTK+3 version is 3.14.9.

**Comment by fstirlitz** [comment]
I think you can consider it fixed. But I cannot guarantee it will stay that way. GTK developers make no effort to keep theming sane or stable. (Look at what happened to Xfce themes…)

Someone fork this toolkit. Please.
